# Generated by Django 5.2.7 on 2025-10-03 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCapturada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=100)),
                ('imagem', models.ImageField(help_text='Foto capturada', upload_to='fotos_capturadas/')),
                ('data_captura', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foto Capturada',
                'verbose_name_plural': 'Fotos Capturadas',
                'ordering': ['-data_captura'],
            },
        ),
    ]
