# Generated by Django 5.2.7 on 2025-10-03 23:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fotocapturada_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropriedadeRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=200, verbose_name='Nome da Propriedade')),
                ('proprietario', models.CharField(max_length=200, verbose_name='Nome do Proprietário')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Área em Hectares')),
                ('agrotoxico_utilizado', models.CharField(max_length=200, verbose_name='Agrotóxico Proibido Utilizado')),
                ('nivel_impacto', models.IntegerField(choices=[(1, 'Nível 1 - Baixo Impacto'), (2, 'Nível 2 - Médio Impacto'), (3, 'Nível 3 - Alto Impacto')], verbose_name='Nível de Impacto Ambiental')),
                ('descricao_impacto', models.TextField(help_text='Descreva os impactos observados nos lençóis freáticos, rios e mares', verbose_name='Descrição do Impacto')),
                ('data_identificacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Identificação')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro Ativo')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Propriedade Rural',
                'verbose_name_plural': 'Propriedades Rurais',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
