# Generated by Django 5.2.7 on 2025-10-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_perfil',
            field=models.CharField(choices=[('COMUM', 'Usuário Comum'), ('DIRETOR', 'Diretor de Divisões'), ('MINISTRO', 'Ministro do Meio Ambiente')], default='COMUM', max_length=10, verbose_name='Tipo de Perfil'),
        ),
    ]
